module.exports = {
  "extends": "eslint:recommended",
  "rules": {
    "array-bracket-spacing": [2, "never"],
    "block-spacing": [2, "always"],
    "brace-style": [2, "1tbs", { "allowSingleLine": true }],
    "camelcase": [2, { "properties": "always" }],
    "comma-style": [2, "last"],
    "curly": 2,
    "dot-notation": 2,
    "eqeqeq": 2,
    "func-style": [2, "declaration"],
    "indent": [2, 2, { "SwitchCase": 1 }],
    "key-spacing": 2,
    "keyword-spacing": 2,
    "linebreak-style": [2, "unix"],
    "new-cap": 2,
    "new-parens": 2,
    "no-console": 0,
    "no-eval": 2,
    "no-extra-semi": 2,
    "no-mixed-spaces-and-tabs": 2,
    "no-process-env": 2,
    "no-return-assign": 2,
    "no-script-url": 2,
    "no-self-compare": 2,
    "no-sequences": 2,
    "no-spaced-func": 2,
    "no-trailing-spaces": 2,
    "object-curly-spacing": [2, "always"],
    "quote-props": 2,
    "radix": 2,
    "semi": [2, "always"],
    "space-before-blocks": 2,
    "space-before-function-paren": [2, "never"],
    "space-infix-ops": 2,
    "space-unary-ops": 2,
    "spaced-comment": [2, "always"],
    "valid-jsdoc": [2, {}],
    "wrap-iife": [2, "inside"]
  }
};
